### ISSUE TITLE
Fix unit tests for latest scigraph compatibility

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-cypher-queries#12]
From https://github.com/SciGraph/SciGraph/pull/225#issuecomment-304353081

There were some changes to the way SciGraph parses and stores swagger yaml metadata. It now uses the data modes defined by SwaggerParser instead of custom beans.

We will need to update the tests here: https://github.com/monarch-initiative/monarch-cypher-queries/tree/master/src/test/java/org/monarchinitiative

**Comment by benwbooth** [comment]
It looks like the broken module, `src/test/java/org/monarchinitiative/CypherResources`, was written to parse a non-existent yaml file, `queries_monarch.yaml`, which would have had some swagger 1.0-formatted yaml metadata. That yaml metadata would have been used to drive a test case called `diseaseFromPhenotype_test` in the `CypherQueryTest` module. The `diseaseFromPhenotype_test` is annotated with `@Ignore`, so will be skipped by the test suite. Its comment reads `Example of a test`.

It looks like a disabled example test case that was never completed but that depends on SciGraph's obsolete swagger 1.0 data models. I can either remove the test case or comment it out.

**Comment by kshefchek** [comment]
If it's already being ignored, I vote for commenting it out.  We can come back to testing the dynamic queries - many are outdated and should be removed anyway in favor of using biolink.
