### ISSUE TITLE
Add upper bound between sequence features and genotypes

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-cypher-queries#18]
We could improve our query performance by establishing an upper bound (distance) between a sequence features and associated genotypes.  For example:

    (feature)<-[:BFO:0000051!*]-(genotype:genotype)
    (allele)-[:BFO:0000051!*]->(feature)

@mbrush is there a maximum distance we can expect given our current modelling?

**Comment by cmungall** [comment]
it should be possible to determine the current upper bound with an aggregate (max) query?
